- name: Hello World Sample
  hosts: all
  tasks:
    -name: get IPs
      debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']
      debug: var=hostvars[inventory_hostname]['ansible_default_ipv6']['address']
